---
include:
  - ./reports/compose.yml
  - ./test-suites/compose.yml

services:
  backchannel:
    build:
      context: implementation/
    labels:
      - traefik.enable=true
      - traefik.http.routers.backchannel.rule=Host(`backchannel.docker.localhost`)
      - traefik.http.routers.backchannel.entrypoints=web
      - traefik.http.services.backchannel.loadbalancer.server.port=8000

  traefik:
    image: traefik:v3.1
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro