---
services:
  vc-data-model-v2-test-suite:
    build: https://github.com/w3c/vc-data-model-2.0-test-suite.git
    depends_on:
      - implementation
    entrypoint: ["./run.sh"]
    # command: >
    #   bash -c "npm i
    #   && npx mocha tests/
    #   && ./send_results.sh"
    environment:
      PROJECT_ID: vc-data-model-v2
    volumes:
      - ./run.sh:/test-suite/run.sh
      - ./send_results.sh:/test-suite/send_results.sh
      - ./localConfig.cjs:/test-suite/localConfig.cjs
