---
services:
  vc-data-model-v2-test-suite:
    container_name: vc-data-model-v2
    build:
      context: https://github.com/w3c/vc-data-model-2.0-test-suite.git#docker
    depends_on:
      - implementation
    entrypoint: ["./run.sh"]
    environment:
      PROJECT_ID: vc-data-model-v2
    volumes:
      - ./send_results.sh:/test-suite/send_results.sh
      - ./run.sh:/test-suite/run.sh
      - ../localConfig.cjs:/test-suite/localConfig.cjs
    labels:
      - traefik.enable=true
      - traefik.http.routers.vc-data-model-v2-test-suite.rule=Host(`vcdm.docker.localhost`)
      - traefik.http.routers.vc-data-model-v2-test-suite.entrypoints=web
      - traefik.http.services.vc-data-model-v2-test-suite.loadbalancer.server.port=8080
  # vc-jose-cose-test-suite:
  #   build:
  #     context: https://github.com/w3c/vc-jose-cose-test-suite.git
  # vc-di-ecdsa-test-suite:
  #   build:
  #     context: https://github.com/w3c/vc-di-ecdsa-test-suite.git
  # vc-di-eddsa-test-suite:
  #   build:
  #     context: https://github.com/w3c/vc-di-eddsa-test-suite.git
  # vc-di-bbs-test-suite:
  #   build:
  #     context: https://github.com/w3c/vc-di-bbs-test-suite.git
  # vc-bitstring-status-list-test-suite :
  #   build:
  #     context: https://github.com/w3c/vc-bitstring-status-list-test-suite.git
