---
services:
  implementation:
    build:
      context: example/
    labels:
      - traefik.enable=true
      - traefik.http.routers.implementation.rule=Host(`implementation.docker.localhost`)
      - traefik.http.routers.implementation.entrypoints=web
      - traefik.http.services.implementation.loadbalancer.server.port=8000